config:
  instignore:
  - '*/.DS_Store'
  upignore:
  - '*/.DS_Store'
  backup: false
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  ignore_missing_in_dotdrop: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  minversion: 1.14.0
variables:
  keyid: 9D41FF247926E119
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    upignore:
    - .local-history
    - lua/compiled.lua
    cmpignore:
    - .local-history
    - lua/compiled.lua
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_popuptmux.sh:
    src: local/bin/popuptmux.sh
    dst: ~/.local/bin/popuptmux.sh
    chmod: '755'
profiles:
  shiwei-mbp:
    dotfiles:
    - f_zshrc
    - d_kitty
    - d_nvim
    - f_tmux.conf
    - f_popuptmux.sh
trans_install:
  gpg: gpg -q --for-your-eyes-only --no-tty -d {0} > {1}
  gpgdir: mkdir {1} && gpg -q --for-your-eyes-only --no-tty -d {0} |tar -x -C {1}
trans_update:
  gpg: gpg -qaer {{@@ keyid @@}} -o- {0} > {1}
  gpgdir: tar -c -C {0} . | gpg -qaer {{@@ keyid @@}} -o {1}
