return {
  'nvim-treesitter/nvim-treesitter',
  -- @type TSConfig
  opts = {
    ensure_installed = {
      'bash',
      'css',
      'dockerfile',
      'html',
      'json',
      'javascript',
      'prisma',
      'json',
      'json5',
      'jsonc',
      'python',
      'go',
      'lua',
      'markdown',
      'markdown_inline',
      'pug',
      'ruby',
      'scss',
      'tsx',
      'dart',
      'typescript',
      'rust',
      'vim',
      'vue',
      'yaml',
      'toml',
    },
    highlight = {
      enable = true,
      disable = {},
    },
  },
}
