
# 设置字体
font:
  normal:
    family: 'BlexMono Nerd Font'
    style: Light
  bold:
    family: 'BlexMono Nerd Font'
    style: Book
  italic:
    family: 'BlexMono Nerd Font'
    style: 'Light Italic'
  bold_italic:
    family: 'JetBrainsMono Nerd Font'
    style: Italic

  # 字大小
  size: 15.0

  offset:
    x: 0
    y: 10
  glyph_offset:
    x: 0
    y: 0

window:
  opacity: 1
  padding:
    x: 0
    y: 0
  startup_mode: Maximized
  decorations: buttonless
  dimensions:
    columns: 0
    lines: 0

scrolling:
  # 回滚缓冲区中的最大行数,指定“0”将禁用滚动。
  history: 100000
  # 滚动行数
  multiplier: 4

cursor:
  style:
    shape: Beam

# 如果为‘true’，则使用亮色变体绘制粗体文本。
draw_bold_text_with_bright_colors: false

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

key_bindings:
  - { key: R, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  - { key: R, mods: Command, mode: ~Vi|~Search, action: ClearHistory }
  - { key: W, mods: Command, action: Hide }
  - { key: W, mods: Command|Shift, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: T, mods: Command, action: CreateNewWindow }
  - { key: Left, mods: Alt, chars: "\x1bb" } # Skip word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # Skip word right
  - { key: Left, mods: Command, chars: "\x01" } # Home
  - { key: Right, mods: Command, chars: "\x05" } # End
  - { key: Back, mods: Command, chars: "\x15" } # Delete line
  - { key: Back, mods: Alt, chars: "\x1b\x7f" } # Delete word

schemes:
  gruvbox: &gruvbox
    primary:
      background: "#1d2021"
      foreground: "#ebdbb2"
    normal:
      black: "#282828"
      red: "#cc241d"
      green: "#98971a"
      yellow: "#d79921"
      blue: "#458588"
      magenta: "#b16286"
      cyan: "#689d6a"
      white: "#a89984"

    # Bright colors
    bright:
      black: "#928374"
      red: "#fb4934"
      green: "#b8bb26"
      yellow: "#fabd2f"
      blue: "#83a598"
      magenta: "#d3869b"
      cyan: "#8ec07c"
      white: "#ebdbb2"
    cursor:
      cursor: "#fbfbfb"

  gruvbox-material: &gruvbox-material
    primary:
      background: "#282828"
      foreground: "#eeffff"

    # Normal colors
    normal:
      black: "#282828" # Arbitrary
      red: "#e53935"
      green: "#91b859"
      yellow: "#ffb62c"
      blue: "#6182b8"
      magenta: "#ff5370" # Dark pink of the original material theme
      cyan: "#39adb5"
      white: "#a0a0a0" # Arbitrary

    # Bright colors
    bright:
      black: "#928374"
      red: "#ff5370"
      green: "#c3e88d"
      yellow: "#ffcb6b"
      blue: "#82aaff"
      magenta: "#f07178" # Pink of the original material theme
      cyan: "#89ddff"
      white: "#ffffff" # Arbitrary
    cursor:
      cursor: "#fbfbfb"

  tokyonight-storm: &tokyonight-storm # Default colors
    primary:
      background: "#24283b"
      foreground: "#c0caf5"

    # Normal colors
    normal:
      black: "#1d202f"
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#bb9af7"
      cyan: "#7dcfff"
      white: "#a9b1d6"

    # Bright colors
    bright:
      black: "#414868" # used in venv name and branch
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#bb9af7"
      cyan: "#7dcfff"
      white: "#c0caf5"

    indexed_colors:
      - { index: 16, color: "#ff9e64" }
      - { index: 17, color: "#db4b4b" }

  tokyonight-day: &tokyonight-day
    primary:
      background: "#e1e2e7"
      foreground: "#3760bf"

    # Normal colors
    normal:
      black: "#e9e9ed"
      red: "#f52a65"
      green: "#587539"
      yellow: "#8c6c3e"
      blue: "#2e7de9"
      magenta: "#9854f1"
      cyan: "#007197"
      white: "#6172b0"

      # Bright colors
      bright:
        black: "#a1a6c5"
        red: "#f52a65"
        green: "#587539"
        yellow: "#8c6c3e"
        blue: "#2e7de9"
        magenta: "#9854f1"
        cyan: "#007197"
        white: "#3760bf"

    indexed_colors:
      - { index: 16, color: "#b15c00" }
      - { index: 17, color: "#c64343" }

    # cursor:
    #   cursor: '#c0caf5'
  gruvbox-flat: &gruvbox-flat
    primary:
      background: "#282828"
      foreground: "#d4be98"

    # Normal colors
    normal:
      black: "#262627"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"

    # Bright colors
    bright:
      black: "#1d2021"
      red: "#ea6962"
      green: "#a9b665"
      yellow: "#d8a657"
      blue: "#7daea3"
      magenta: "#d3869b"
      cyan: "#89b482"
      white: "#d4be98"

    indexed_colors:
      - { index: 16, color: "#e78a4e" }
      - { index: 17, color: "#c14a4a" }

colors: *tokyonight-storm
